### ISSUE TITLE
Running in MacOS not working

### ISSUE THREAD

**Issue by CrispyBacon1999** [SleipnirGroup/UntitledWaypointEditor#56]
Whenever I try to run the program on MacOS (Intel Silicon), I'm getting issues with it finding the dylib for `/usr/local/lib/libTrajoptLib.dylib`. I get the error of
```
dyld[53276]: Library not loaded: @rpath/libTrajoptLib.dylib
  Referenced from: <A497B11A-EBBB-325A-9BD5-006564060FE6> /Users/bacon/dev/frc/UntitledWaypointEditor/src-tauri/target/debug/untitled-waypoint-editor
  Reason: tried: '/Users/bacon/dev/frc/UntitledWaypointEditor/src-tauri/target/debug/libTrajoptLib.dylib' (no such file), '/Users/bacon/dev/frc/UntitledWaypointEditor/src-tauri/target/debug/libTrajoptLib.dylib' (no such file), '/usr/local/lib/libTrajoptLib.dylib' (no such file), '/usr/lib/libTrajoptLib.dylib' (no such file, not in dyld cache)
```

Is there a step that's not included in the readme that I'm missing?

Note: I've tried setting `LD_LIBRARY_PATH` and it doesn't seem to affect anything.

**Comment by jlbabilino** [comment]
You can copy all files matching the pattern `target/debug/build/trajoptlib-*/out/lib/*.dylib` to `target/debug/`. This is what you can do temporarily until we come up with a better solution of automatically finding the dependent dynamic libraries.

**Comment by jlbabilino** [comment]
I haven’t put it in the README because ideally it shouldn’t be a required step, but maybe it should be there at least temporarily.
